function animSwitch(argument0) {
	animId = argument0;

	switch(animId)
	{
		case -1: break;
		case 0: fightAnimA(spr_slashAnim);
		break;
		case 1: defAnimA();
		break;
		case 2: flashAnimA();
		break;
		case 3: hatchAnimA();
		break;
		case 4: lightningAnimA();
		break;
		case 5: iceAnimA();
		break;
		case 6: webAnimA();
		break;
		case 7: shadAnimA();
		break;
		case 8: flameAnimA();
		break;
		case 9: mindAnimA();
		break;
		case 10: vitalAnimA();
		break;
		case 11: healAnimA();
		break;
		case 12: etherAnimA();
		break;
		case 13: deathAnimA();
		break;
		case 14: poisonAnimA();
		break;
		case 15: lightAnimA();
		break;
		case 16: firestormAnimA();
		break;
		case 17: blizzardAnimA();
		break;
		case 18: thunderAnimA();
		break;
		case 19: fightAnimA(spr_crushAnim);
		break;
		case 20: fightAnimA(spr_slashAnim);
		break;
		case 21: fightAnimA(spr_stabAnim);
		break;
		case 22: waveAnimA();
		break;
		case 23: slimeAnimA();
		break;
		case 24: rootAnim();
		break;
		case 25: sleepAnimA();
		break;
		case 26: voidAnimA();
		break;
		case 27: mistAnimA();
		break;
		case 28: flashAnimB();
		break;
		case 29: boostAnimA();
		break;
		case 30: gravAnimA();
		break;
		case 31: meteorAnimA();
		break;
		case 32: digAnim();
		break;
		case 33: paraAnimA();
		break;
		case 34: massParalysisAnim();
		break;
		case 35: magicMissileAnimA();
		break;
		case 36: shieldAnimA();
		break;
		case 37: massTeleportAnim();
		break;
		case 38: poisonGasAnim();
		break;
		case 39: disasterAnimA();
		break;
		case 40: teleportAnim();
		break;
		case 41: dispelAnimA();
		break;
		case 42: infernoAnimA();
		break;
		case 43: plasmaAnim();
		break;
		case 44: extinctionAnim();
		break;
		case 45: fightAnimA(spr_musicAttack);
		break;
		case 46: necroticBreathAnim();
		break;
		case 47: featherAnim();
		break;
		case 48: lightningBreathAnim();
		break;
		case 49: coldBreathAnim();
		break;
		case 50: eyeBeamAnim();
		break;
		case 51: fireBreathAnim();
		break;
		case 52: immolateAnim();
		break;
		case 53: venomBreathAnim();
		break;
		case 54: psychoticBreathAnim();
		break;
		case 55: aetherialBreathAnim();
		break;
		case 56: poisonShockAnim();
		break;
		case 57: absoluteZeroAnim();
		break;
		case 58: earthquakeAnim();
		break;
		case 59: bulwarkAnim();
		break;
		case 60: holyAnim();
		break;
		case 61: sunlightAnim();
		break;
		case 62: citadelAnim();
		break;
		case 63: groupHealAnim();
		break;
		case 64: markForDeathAnim();
		break;
		case 65: grandHealAnim();
		break;
		case 66: blizzardAnimB();
		break;
		case 67: tremorAnim();
		break;
		
	}


}
